#!/bin/sh

usage() {
  e=$1
  echo "Usage:"
  echo "  $(basename $0) [-h|--help]"
  echo "    This help"
  echo "  $(basename $0) [-s] [-e] -c <CA> <key-name>"
  echo "    Create a key with a signing request for CA"
  echo "    -s: Create a sub-CA signing request"
  echo "    -e: Encrypt the private key with des3"
  if [ "$e" ]; then exit $e; fi
}

unset encrypt subca

if [ "$1" = "--help" ]; then usage 0; fi
while getopts "c:es" arg; do
  case $arg in
    c) CA=$OPTARG ;;
    e) encrypt=1 ;;
    s) subca=1 ;;
    h) usage 0 ;;
    ?) usage 1 ;;
  esac
done
shift $(expr $OPTIND - 1)
name="$1"
if [ -z "$CA" -o -z "$name" ]; then usage 1; fi
export CA

cd ${PKIDIR:-/srv/pki}
if ! tmp=$(mktemp -d); then
  echo Cannot create temporary directory. >&2
  exit -1
fi
trap "rm -fr $tmp" EXIT

set -e

export default_o="${default_o:-$CA}"
export default_ou="${default_ou:-Invalid}"
export default_cn="${default_cn:-$name${subca:+ Sub-CA}}"
openssl req -config pki.conf -new -newkey rsa -keyout $tmp/key -text -out "$CA/requests/$name" -passout pass:password ${subca:+-reqexts req_subca_extensions}
chmod 400 "$CA/requests/$name"
openssl rsa -in $tmp/key -passin pass:password ${encrypt:+-des3} -text -out "$CA/keys/$name"
chmod 400 "$CA/keys/$name"

