#!/bin/sh

usage() {
  e=$1
  echo "Usage:"
  echo "  $(basename $0) [-h|--help]"
  echo "    This help"
  echo "  $(basename $0) [-s] -c <CA> <key-name>"
  echo "    Sign request with CA"
  echo "    -s: Create a sub-CA certificate"
  if [ "$e" ]; then exit $e; fi
}

unset subca
if [ "$1" = "--help" ]; then usage 0; fi
while getopts "c:s" arg; do
  case $arg in
    c) CA=$OPTARG ;;
    s) subca=1 ;;
    h) usage 0 ;;
    ?) usage 1 ;;
  esac
done
shift $(expr $OPTIND - 1)
name="$1"
if [ -z "$CA" -o -z "$name" ]; then usage 1; fi
export CA

cd ${PKIDIR:-/srv/pki}

set -e

if [ -z "$CRL_URL" ]; then
  CRL_URL=$(grep -A3 CRL\ Distrib "$CA/certificates/CA" | sed -n 's/.*URI://p')
fi
export CRL_URL=${CRL_URL:+URI:$CRL_URL}
openssl ca -config pki.conf -in "$CA/requests/$name" -out "$CA/certificates/$name" ${subca:+-extensions ca_subca_extensions -policy subca_policy}
